import eUkraine from "@/assets/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Sant Crois",
    description: "Generated by create next app",
    viewport: {
        width: "device-width",
        initialScale: 1,
        maximumScale: 1,
        viewportFit: "cover",
    },
    icons: {
        icon: "/favicon.ico",
    },
};

export default function ServerLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={eUkraine.variable}>{children}</body>
        </html>
    );
}
